## Install Dependencies

In [ ]:
# !pip install mediapipe opencv-python pandas scikit-learn

## 1. Detection

In [1]:
from mediapipe import solutions as mp
import cv2

In [2]:
cap = cv2.VideoCapture(0)
# Initiate holistic model
with mp.holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:

    while cap.isOpened():
        ret, frame = cap.read()

        # Recolor Feed
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        # Make Detections
        results = holistic.process(image)

        # Recolor for rendering
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

        # Draw Face Landmarks
        mp.drawing_utils.draw_landmarks(image, results.face_landmarks, mp.holistic.FACE_CONNECTIONS,
                                        mp.drawing_utils.DrawingSpec(
                                            color=(242, 216, 175), thickness=1, circle_radius=1),
                                        mp.drawing_utils.DrawingSpec(color=(242, 216, 175), thickness=1))

        # Right Hand
        mp.drawing_utils.draw_landmarks(image, results.right_hand_landmarks, mp.holistic.HAND_CONNECTIONS,
                                        mp.drawing_utils.DrawingSpec(
                                            color=(181, 137, 82), thickness=2, circle_radius=4),
                                        mp.drawing_utils.DrawingSpec(color=(181, 137, 82), thickness=2))

        # Left Hand
        mp.drawing_utils.draw_landmarks(image, results.left_hand_landmarks, mp.holistic.HAND_CONNECTIONS,
                                        mp.drawing_utils.DrawingSpec(
                                            color=(181, 137, 82), thickness=2, circle_radius=4),
                                        mp.drawing_utils.DrawingSpec(color=(181, 137, 82), thickness=2))

        # Pose Detection
        mp.drawing_utils.draw_landmarks(image, results.pose_landmarks, mp.holistic.POSE_CONNECTIONS,
                                        mp.drawing_utils.DrawingSpec(
                                            color=(65, 53, 31), thickness=2, circle_radius=2),
                                        mp.drawing_utils.DrawingSpec(color=(65, 53, 31), thickness=2))

        cv2.imshow("Holistic Model Detection", image)

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()

In [3]:
results.pose_landmarks

landmark {
  x: 0.5631622
  y: 0.42167315
  z: -1.3431389
  visibility: 0.99979615
}
landmark {
  x: 0.6048206
  y: 0.33011836
  z: -1.239659
  visibility: 0.99966633
}
landmark {
  x: 0.63138545
  y: 0.33519587
  z: -1.2397289
  visibility: 0.9995985
}
landmark {
  x: 0.65656835
  y: 0.340359
  z: -1.239447
  visibility: 0.9995414
}
landmark {
  x: 0.5207145
  y: 0.31932944
  z: -1.2450023
  visibility: 0.9997384
}
landmark {
  x: 0.49170572
  y: 0.3174241
  z: -1.2447907
  visibility: 0.9997717
}
landmark {
  x: 0.46574417
  y: 0.31649175
  z: -1.2446669
  visibility: 0.9997998
}
landmark {
  x: 0.6845988
  y: 0.38510036
  z: -0.6313408
  visibility: 0.9995688
}
landmark {
  x: 0.4309438
  y: 0.36301357
  z: -0.6313986
  visibility: 0.99974644
}
landmark {
  x: 0.608605
  y: 0.5179623
  z: -1.1006902
  visibility: 0.9997986
}
landmark {
  x: 0.50667864
  y: 0.5065352
  z: -1.105552
  visibility: 0.9997949
}
landmark {
  x: 0.83067703
  y: 0.8335135
  z: -0.25149566
  visibility: 0.99

## 2. Capture Landmarks & Export to CSV

### Open and Write Columns Head in CSV 

In [4]:
import csv
import os
import numpy as np

In [5]:
num_coords = len(results.pose_landmarks.landmark) + \
    len(results.face_landmarks.landmark) + \
    len(results.right_hand_landmarks.landmark)
num_coords

522

In [6]:
landmarks = ['class']
for val in range(1, num_coords+1):
    landmarks += ['x{}'.format(val), 'y{}'.format(val),
                  'z{}'.format(val), 'v{}'.format(val)]

In [12]:
with open("coords.csv", mode="w", newline="" ) as f:
    csv_writer = csv.writer(f, delimiter=",", quotechar='"',quoting=csv.QUOTE_MINIMAL)
    csv_writer.writerow(landmarks)

### Capture and Extract Features of Assigned Class

- Repeat this step to save features of different targets.
- Make sure your samples covered different scenario of the target for better detection.

In [46]:
class_name = "s"

In [47]:
cap = cv2.VideoCapture(0)
# Initiate holistic model
with mp.holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:

    while cap.isOpened():
        ret, frame = cap.read()

        # Recolor Feed
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        # Make Detections
        results = holistic.process(image)

        # Recolor for rendering
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

        # Draw Face Landmarks
        mp.drawing_utils.draw_landmarks(image, results.face_landmarks, mp.holistic.FACE_CONNECTIONS,
                                        mp.drawing_utils.DrawingSpec(
                                            color=(242, 216, 175), thickness=1, circle_radius=1),
                                        mp.drawing_utils.DrawingSpec(color=(242, 216, 175), thickness=1))

        # Right Hand
        mp.drawing_utils.draw_landmarks(image, results.right_hand_landmarks, mp.holistic.HAND_CONNECTIONS,
                                        mp.drawing_utils.DrawingSpec(
                                            color=(181, 137, 82), thickness=2, circle_radius=4),
                                        mp.drawing_utils.DrawingSpec(color=(181, 137, 82), thickness=2))

        # Left Hand
        mp.drawing_utils.draw_landmarks(image, results.left_hand_landmarks, mp.holistic.HAND_CONNECTIONS,
                                        mp.drawing_utils.DrawingSpec(
                                            color=(181, 137, 82), thickness=2, circle_radius=4),
                                        mp.drawing_utils.DrawingSpec(color=(181, 137, 82), thickness=2))

        # Pose Detection
        mp.drawing_utils.draw_landmarks(image, results.pose_landmarks, mp.holistic.POSE_CONNECTIONS,
                                        mp.drawing_utils.DrawingSpec(
                                            color=(65, 53, 31), thickness=2, circle_radius=2),
                                        mp.drawing_utils.DrawingSpec(color=(65, 53, 31), thickness=2))
        # Export coordinates
        try:
            # Extract pose landmarks
            try: 
                pose = results.pose_landmarks.landmark
                pose_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in pose]).flatten())
            except:
                pose_row=list(np.zeros(33*4))
                
            # Extract face landmarks
            try:
                face = results.face_landmarks.landmark
                face_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in face]).flatten())
            except:
                face_row=list(np.zeros(468*4))
            
            # Extract right hand landmarks
            try:
                right_hand = results.right_hand_landmarks.landmark
                right_hand_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in right_hand]).flatten())
            except:
                right_hand_row=list(np.zeros(21*4))
           
            #Concate row
            row = pose_row + face_row + right_hand_row
            
            # Append class name
            row.insert(0, class_name)
            
            # Export to CVS
            with open("coords.csv", mode="a", newline="" ) as f:
                csv_writer = csv.writer(f, delimiter=",", quotechar='"',quoting=csv.QUOTE_MINIMAL)
                csv_writer.writerow(row)
        
        except:
            pass
        
        cv2.imshow("Holistic Model Detection", image)

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()

## 3. Train Custom Model Using Scikit Learn

### Read in Collected Data and Process

In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [28]:
df = pd.read_csv("coords.csv")

In [29]:
df

class        x1        y1        z1        v1        x2        y2  \
0           hi  0.556992  0.413627 -1.814404  0.999789  0.589199  0.319133   
1           hi  0.555315  0.407389 -1.432199  0.999792  0.588943  0.315282   
2           hi  0.554900  0.400514 -1.498092  0.999723  0.589004  0.309599   
3           hi  0.553700  0.396480 -1.356619  0.999513  0.588916  0.304934   
4           hi  0.552426  0.392922 -1.364183  0.999483  0.588827  0.301778   
..         ...       ...       ...       ...       ...       ...       ...   
141  thumbs up  0.576962  0.380177 -1.490147  0.999725  0.611919  0.292289   
142  thumbs up  0.574371  0.379922 -1.354042  0.999742  0.610366  0.291790   
143  thumbs up  0.571804  0.379614 -1.357790  0.999753  0.609271  0.290567   
144  thumbs up  0.571645  0.379724 -1.481499  0.999748  0.609231  0.290581   
145  thumbs up  0.569543  0.378187 -1.462819  0.999759  0.608738  0.289038   

           z2        v2        x3  ...      z520  v520      x521      y521  \
0   -1.734257  0.999624  0.613905  ...  0.000000   0.0  0.000000  0.000000   
1   -1.352080  0.999622  0.613447  ...  0.000000   0.0  0.000000  0.000000   
2   -1.423380  0.999536  0.613474  ...  0.000000   0.0  0.000000  0.000000   
3   -1.280517  0.999299  0.613362  ...  0.000000   0.0  0.000000  0.000000   
4   -1.279958  0.999238  0.613210  ...  0.000000   0.0  0.000000  0.000000   
..        ...       ...       ...  ...       ...   ...       ...       ...   
141 -1.400127  0.999582  0.636821  ... -0.289640   0.0  0.259056  0.745017   
142 -1.261753  0.999610  0.635785  ...  0.000000   0.0  0.000000  0.000000   
143 -1.268046  0.999630  0.635091  ... -0.308373   0.0  0.256559  0.766909   
144 -1.389240  0.999633  0.635000  ... -0.335170   0.0  0.266689  0.764719   
145 -1.371749  0.999651  0.634824  ... -0.332492   0.0  0.263620  0.757960   

         z521  v521      x522      y522      z522  v522  
0    0.000000   0.0  0.000000  0.000000  0.000000   0.0  
1    0.000000   0.0  0.000000  0.000000  0.000000   0.0  
2    0.000000   0.0  0.000000  0.000000  0.000000   0.0  
3    0.000000   0.0  0.000000  0.000000  0.000000   0.0  
4    0.000000   0.0  0.000000  0.000000  0.000000   0.0  
..        ...   ...       ...       ...       ...   ...  
141 -0.268989   0.0  0.245709  0.739899 -0.266425   0.0  
142  0.000000   0.0  0.000000  0.000000  0.000000   0.0  
143 -0.301880   0.0  0.240665  0.760832 -0.310947   0.0  
144 -0.346481   0.0  0.256567  0.761431 -0.371042   0.0  
145 -0.348450   0.0  0.258075  0.755765 -0.371836   0.0  

[146 rows x 2089 columns]

In [30]:
X = df.drop("class", axis=1)
y = df["class"]

In [31]:
y.value_counts()

thumbs up    59
happy        45
hi           42
Name: class, dtype: int64

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=47)

### Train A Machine Learning Classification Model

In [33]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [34]:
pipelines = {
    "lr":make_pipeline(StandardScaler(), LogisticRegression()),
    "svc":make_pipeline(StandardScaler(), SVC()),
    "rf":make_pipeline(StandardScaler(), RandomForestClassifier()),
    "knn":make_pipeline(StandardScaler(), KNeighborsClassifier()),
}

In [35]:
fit_models = {}
for algo, pipeline in pipelines.items():
    model = pipeline.fit(X_train, y_train.ravel())
    fit_models[algo] = model

C:\Users\ADMIN\AppData\Roaming\Python\Python38\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [36]:
fit_models["rf"].predict(X_test)

array(['hi', 'thumbs up', 'thumbs up', 'hi', 'thumbs up', 'hi',
       'thumbs up', 'thumbs up', 'happy', 'hi', 'happy', 'thumbs up',
       'thumbs up', 'thumbs up', 'happy', 'happy', 'thumbs up', 'happy',
       'thumbs up', 'hi', 'thumbs up', 'thumbs up', 'thumbs up',
       'thumbs up', 'thumbs up', 'thumbs up', 'hi', 'hi', 'thumbs up',
       'thumbs up'], dtype=object)

### Evaluate and Serialize Model

In [37]:
from sklearn.metrics import accuracy_score, confusion_matrix
import pickle
import os

In [38]:
for algo, model in fit_models.items():
    pred = model.predict(X_test)
    print(algo, accuracy_score(y_test, pred))

lr 0.9333333333333333
svc 0.8666666666666667
rf 0.9
knn 0.8666666666666667


In [41]:
for algo, model in fit_models.items():
    pred = model.predict(X_test)
    print(algo, confusion_matrix(y_test, pred), sep="\n", end="\n\n")

lr
[[ 5  0  0]
 [ 0  8  2]
 [ 0  0 15]]

svc
[[ 5  0  0]
 [ 0  6  4]
 [ 0  0 15]]

rf
[[ 5  0  0]
 [ 0  7  3]
 [ 0  0 15]]

knn
[[ 5  0  0]
 [ 0  6  4]
 [ 0  0 15]]



In [42]:
if not os.path.exists("generated_model/"):
    os.mkdir("generated_model/")
    
with open("generated_model/body_language.pkl", "wb") as f:
    pickle.dump(fit_models["rf"], f)

## 4. Make Detections with Model

In [43]:
with open("generated_model/body_language.pkl", "rb") as f:
    model_inference = pickle.load(f)

In [45]:
cap = cv2.VideoCapture(0)
# Initiate holistic model
with mp.holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:

    while cap.isOpened():
        ret, frame = cap.read()

        # Recolor Feed
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        # Make Detections
        results = holistic.process(image)


        # Recolor for rendering
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

        # Draw Face Landmarks
        mp.drawing_utils.draw_landmarks(image, results.face_landmarks, mp.holistic.FACE_CONNECTIONS,
                                        mp.drawing_utils.DrawingSpec(
                                            color=(242, 216, 175), thickness=1, circle_radius=1),
                                        mp.drawing_utils.DrawingSpec(color=(242, 216, 175), thickness=1))

        # Right Hand
        mp.drawing_utils.draw_landmarks(image, results.right_hand_landmarks, mp.holistic.HAND_CONNECTIONS,
                                        mp.drawing_utils.DrawingSpec(
                                            color=(181, 137, 82), thickness=2, circle_radius=4),
                                        mp.drawing_utils.DrawingSpec(color=(181, 137, 82), thickness=2))

        # Left Hand
        mp.drawing_utils.draw_landmarks(image, results.left_hand_landmarks, mp.holistic.HAND_CONNECTIONS,
                                        mp.drawing_utils.DrawingSpec(
                                            color=(181, 137, 82), thickness=2, circle_radius=4),
                                        mp.drawing_utils.DrawingSpec(color=(181, 137, 82), thickness=2))

        # Pose Detection
        mp.drawing_utils.draw_landmarks(image, results.pose_landmarks, mp.holistic.POSE_CONNECTIONS,
                                        mp.drawing_utils.DrawingSpec(
                                            color=(65, 53, 31), thickness=2, circle_radius=2),
                                        mp.drawing_utils.DrawingSpec(color=(65, 53, 31), thickness=2))
        # Export coordinates
        try:
            # Extract pose landmarks
            try: 
                pose = results.pose_landmarks.landmark
                pose_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in pose]).flatten())
            except:
                pose_row=list(np.zeros(33*4))
                
            # Extract face landmarks
            try:
                face = results.face_landmarks.landmark
                face_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in face]).flatten())
            except:
                face_row=list(np.zeros(468*4))
            
            # Extract right hand landmarks
            try:
                right_hand = results.right_hand_landmarks.landmark
                right_hand_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in right_hand]).flatten())
            except:
                right_hand_row=list(np.zeros(21*4))
           
            #Concate row
            row = pose_row + face_row + right_hand_row
            
            # Prediction
            X = pd.DataFrame([row])
            pred = model_inference.predict(X)[0]
            prob = model_inference.predict_proba(X)[0].round(2)
            print(pred, prob)
            
            # Display coordinates
            coords = tuple(np.multiply(
                            np.array(
                            (results.pose_landmarks.landmark[mp.holistic.PoseLandmark.LEFT_EAR].x, 
                            results.pose_landmarks.landmark[mp.holistic.PoseLandmark.LEFT_EAR].y))
                            , [640, 480]).astype(int))
            
            # Display box
            cv2.rectangle(image,
                          (coords[0], coords[1]+5),
                          (coords[0]+len(pred)*20, coords[1]-30),
                          (245, 117, 16), -1)
            
            # Display predicted class
            cv2.putText(image, pred, coords, cv2.FONT_HERSHEY_SIMPLEX, 
                      1, (255, 255, 255), 2, cv2.LINE_AA)
            
            # Display probability
            cv2.putText(image, str(prob[np.argmax(prob)]), (coords[0]+len(pred)*20, coords[1]-30), cv2.FONT_HERSHEY_SIMPLEX, 
                      0.3, (255, 255, 255), 1, cv2.LINE_AA)
            
            # Status bar
            cv2.rectangle(image, (0,0), (250,60), (245, 117, 16), -1)
            cv2.putText(image, "CLASS", (95,12), cv2.FONT_HERSHEY_SIMPLEX,
                       0.5, (0,0,0), 1, cv2.LINE_AA)
            cv2.putText(image, pred.split(' ')[0], (90,40), cv2.FONT_HERSHEY_SIMPLEX,
                       1, (255, 255, 255), 2, cv2.LINE_AA)
            cv2.putText(image, "PROB", (15,12), cv2.FONT_HERSHEY_SIMPLEX,
                       0.5, (0,0,0), 1, cv2.LINE_AA)
            cv2.putText(image, str(prob[np.argmax(prob)]), (10,40), cv2.FONT_HERSHEY_SIMPLEX,
                       1, (255, 255, 255), 2, cv2.LINE_AA)
            
        
        except:
            pass
        
        cv2.imshow("Holistic Model Detection", image)

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()

thumbs up [0.03 0.34 0.63]
thumbs up [0.04 0.34 0.62]
thumbs up [0.04 0.34 0.62]
thumbs up [0.04 0.34 0.62]
happy [0.69 0.25 0.06]
happy [0.72 0.23 0.05]
happy [0.7  0.24 0.06]
happy [0.66 0.27 0.07]
happy [0.69 0.25 0.06]
happy [0.73 0.21 0.06]
happy [0.75 0.2  0.05]
happy [0.76 0.18 0.06]
happy [0.79 0.15 0.06]
happy [0.62 0.27 0.11]
hi [0.11 0.56 0.33]
hi [0.1  0.65 0.25]
hi [0.12 0.5  0.38]
thumbs up [0.12 0.41 0.47]
thumbs up [0.12 0.42 0.46]
thumbs up [0.12 0.39 0.49]
thumbs up [0.13 0.4  0.47]
thumbs up [0.12 0.37 0.51]
thumbs up [0.12 0.36 0.52]
thumbs up [0.13 0.37 0.5 ]
thumbs up [0.12 0.41 0.47]
thumbs up [0.12 0.43 0.45]
thumbs up [0.12 0.4  0.48]
hi [0.12 0.44 0.44]
thumbs up [0.13 0.38 0.49]
thumbs up [0.13 0.38 0.49]
thumbs up [0.13 0.38 0.49]
thumbs up [0.12 0.39 0.49]
thumbs up [0.12 0.39 0.49]
thumbs up [0.12 0.32 0.56]
thumbs up [0.12 0.37 0.51]
thumbs up [0.12 0.37 0.51]
thumbs up [0.12 0.36 0.52]
thumbs up [0.12 0.33 0.55]
thumbs up [0.12 0.38 0.5 ]
thumbs up [0.12